/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientsActivite;

import ClientsActivite.ListeActivities;
import ProtocoleFUCAMP.RequeteFUCAMP;
import ProtocoleFUCAMP.ReponseFUCAMP;
import Utilities.Utils;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Salva
 */
public class LoginActivite extends javax.swing.JFrame {
    
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    private Socket cliSock;
    public String path = "C:\\Users\\Salva\\Documents\\ecole\\important\\3emeinformatique\\rti\\Inpres-Enjoy your holidays\\JavaServeur\\src\\Config\\Config.config";

    /**
     * Creates new form LoginActivite
     */
    public LoginActivite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Jnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Jmdp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom d'utilisateur");

        Jnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JnomActionPerformed(evt);
            }
        });

        jLabel2.setText("Mot de passe");

        Jmdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmdpActionPerformed(evt);
            }
        });

        jButton1.setText("Se connecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jnom)
                            .addComponent(Jmdp, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jmdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JnomActionPerformed

    private void JmdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JmdpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Jnom.getText() != null && !Jnom.getText().equals("")){
            if(Jmdp.getText() != null && !Jmdp.getText().equals("") ){
                
                String chargeUtile = Jnom.getText()+";"+Jmdp.getText();
                RequeteFUCAMP req = null;
                try {
                    req = new RequeteFUCAMP(RequeteFUCAMP.LOGIN, chargeUtile);
                    
                    // Connexion au serveur
                    ois=null; oos=null; cliSock = null;
                    String adresse = Utils.getItemConfig(path, "adresse");
                    int port = Integer.parseInt(Utils.getItemConfig(path, "PORT_ACTIVITES"));
                    try
                    {
                        cliSock = new Socket(adresse, port);
                        System.out.println(cliSock.getInetAddress().toString());
                    }                       
                    catch (IOException ex) {
                        Logger.getLogger(LoginActivite.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    // Envoie de la requête
                    System.out.println("envoie requete !");
                    try
                    {
                        oos = new ObjectOutputStream(cliSock.getOutputStream());
                        oos.writeObject(req); oos.flush();
                    }
                    catch (IOException e)
                    { System.err.println("Erreur réseau ? [" + e.getMessage() + "]"); }
                    // Lecture de la réponse
                    ReponseFUCAMP rep = null;
                    System.out.println("en attente d'une réponse !");
                    try
                    {
                        ois = new ObjectInputStream(cliSock.getInputStream());
                        rep = (ReponseFUCAMP)ois.readObject();
                        System.out.println(" *** Reponse reçue : " + rep.getChargeUtile());
                        
                        if(rep.getCode()== ReponseFUCAMP.LOGIN_OK){
                            System.out.println("Vous vous etes connecté !");
                           
                            ListeActivities la = new ListeActivities();
                            la.setVisible(true);
                            
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "mot de passe eronné ou identifiant oublié !", "CAUTION ! ", JOptionPane.INFORMATION_MESSAGE);
                            

                        }
                    }
                    catch (ClassNotFoundException e)
                    { System.out.println("--- erreur sur la classe = " + e.getMessage()); }
                    catch (IOException e)
                    { System.out.println("--- erreur IO = " + e.getMessage()); }
                    
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(LoginActivite.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(LoginActivite.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(LoginActivite.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }else
            {
                JOptionPane.showMessageDialog(null, "Veuillez saisir le mot de passe !", "CAUTION ! ", JOptionPane.INFORMATION_MESSAGE);
                
            }
        }else
        {
            JOptionPane.showMessageDialog(null, "Veuillez saisir le nom d'utilisateur !", "CAUTION ! ", JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void Connexion() throws IOException{
        ois=null; oos=null; cliSock = null;
        String adresse = "127.0.0.1";
        int port = Integer.parseInt(Utils.getItemConfig(path, "PORT_ACTIVITES"));
        try
        {
            cliSock = new Socket(adresse, port);
            System.out.println(cliSock.getInetAddress().toString());
        }                       
        catch (IOException ex) {
            Logger.getLogger(LoginActivite.class.getName()).log(Level.SEVERE, null, ex);
        }
        oos = new ObjectOutputStream(cliSock.getOutputStream());
        
        ois = new ObjectInputStream(cliSock.getInputStream());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginActivite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginActivite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginActivite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginActivite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginActivite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jmdp;
    private javax.swing.JTextField Jnom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
